# pylint: skip-file
# (Stub file: docstring/unused-argument rules don't apply to .pyi signatures.)
"""Type stubs for the compiled `py_chunks._rust` extension module.

Enumerated from the pyfunction/pyclass definitions in `src/` (the
`bind_format!` / `bind_per_mode_*!` / `bind_images!` macro expansions plus the
hand-written csv/xlsx/dispatch-bytes bindings).

Conventions:
- Batch chunkers return the ``{"chunks": [...], "rust_ms": float}`` envelope,
  typed here as ``dict[str, Any]``.
- ``*_with_images`` functions return ``(chunks, [(name, bytes), ...])``.
- ``*_to_markdown_with_images`` return ``(markdown, [(name, bytes), ...])``.
- ``ChunkStreamIterator`` (the generic stream iterator used by the
  ``stream_*_chunks`` functions of single-signature formats) is a pyclass that
  is not registered as a module attribute; it is declared here as
  ``_ChunkStreamIterator`` for typing only.
"""

from typing import Any, Iterator

_Chunk = dict[str, Any]
_Envelope = dict[str, Any]
_Images = list[tuple[str, bytes]]
_ImagePair = tuple[list[_Chunk], _Images]
_MarkdownPair = tuple[str, _Images]

class _ChunkStreamIterator(Iterator[_Chunk]):
    def __iter__(self) -> "_ChunkStreamIterator": ...
    def __next__(self) -> dict[str, Any]: ...

class _PerModeIterator(Iterator[_Chunk]):
    def __iter__(self) -> "_PerModeIterator": ...
    def __next__(self) -> dict[str, Any]: ...

# ── Per-mode stream iterator classes (registered module attributes) ──────────

class DocStructuralIterator(_PerModeIterator): ...
class DocSectionIterator(_PerModeIterator): ...
class DocSemanticIterator(_PerModeIterator): ...
class DocSlidingWindowIterator(_PerModeIterator): ...
class DocSentenceIterator(_PerModeIterator): ...
class DocPageAwareIterator(_PerModeIterator): ...
class DocxStructuralIterator(_PerModeIterator): ...
class DocxSectionIterator(_PerModeIterator): ...
class DocxSemanticIterator(_PerModeIterator): ...
class DocxSlidingWindowIterator(_PerModeIterator): ...
class DocxSentenceIterator(_PerModeIterator): ...
class DocxPageAwareIterator(_PerModeIterator): ...
class PptStructuralIterator(_PerModeIterator): ...
class PptSectionIterator(_PerModeIterator): ...
class PptSemanticIterator(_PerModeIterator): ...
class PptSlidingWindowIterator(_PerModeIterator): ...
class PptSentenceIterator(_PerModeIterator): ...
class PptPageAwareIterator(_PerModeIterator): ...
class PptxStreamIterator(_PerModeIterator): ...

class XlsxStreamIterator(Iterator[_Chunk]):
    def __iter__(self) -> "XlsxStreamIterator": ...
    def __next__(self) -> dict[str, Any]: ...

# ── Source-agnostic bytes API (engine dispatch, no filesystem) ───────────────

def get_chunks_from_bytes(
    data: bytes, filename: str, mode: str, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int,
) -> dict[str, Any]: ...
def get_chunks_with_images_from_bytes(
    data: bytes, filename: str, mode: str, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int,
) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def get_markdown_from_bytes(data: bytes, filename: str) -> str: ...
def get_markdown_with_images_from_bytes(data: bytes, filename: str) -> tuple[str, list[tuple[str, bytes]]]: ...
def chunk_csv_from_bytes(
    data: bytes, mode: str, rows_per_chunk: int, window_size: int, overlap: int,
    include_headers: bool, delimiter: int | None = None, encoding: str = "utf-8",
    skip_empty_rows: bool = True,
) -> dict[str, Any]: ...
def csv_to_markdown_from_bytes(
    data: bytes, delimiter: int | None = None, encoding: str = "utf-8",
) -> str: ...

# ── csv / tsv ────────────────────────────────────────────────────────────────

def chunk_csv(
    file_path: str, mode: str, rows_per_chunk: int, window_size: int, overlap: int,
    include_headers: bool, delimiter: int | None = None, encoding: str = "utf-8",
    skip_empty_rows: bool = True,
) -> dict[str, Any]: ...
def chunk_csv_sliding_window(
    file_path: str, window_size: int, overlap: int, include_headers: bool,
    delimiter: int | None = None, encoding: str = "utf-8", skip_empty_rows: bool = True,
) -> dict[str, Any]: ...
def csv_to_markdown(
    file_path: str, delimiter: int | None = None, encoding: str = "utf-8",
) -> str: ...
def stream_csv_chunks(
    file_path: str, mode: str, rows_per_chunk: int, window_size: int, overlap: int,
    include_headers: bool, delimiter: int | None = None, encoding: str = "utf-8",
    skip_empty_rows: bool = True,
) -> _ChunkStreamIterator: ...

# ── doc (Word 97-2003) ───────────────────────────────────────────────────────

def chunk_doc(file_path: str) -> dict[str, Any]: ...
def chunk_doc_section(file_path: str) -> dict[str, Any]: ...
def chunk_doc_semantic(file_path: str) -> dict[str, Any]: ...
def chunk_doc_sliding_window(file_path: str, window_size: int, overlap: int) -> dict[str, Any]: ...
def chunk_doc_sentence(file_path: str, sentences_per_chunk: int) -> dict[str, Any]: ...
def chunk_doc_page_aware(file_path: str, paragraphs_per_page: int) -> dict[str, Any]: ...
def chunk_doc_structural_with_images(file_path: str) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_doc_section_with_images(file_path: str) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_doc_semantic_with_images(file_path: str) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_doc_sliding_window_with_images(
    file_path: str, window_size: int, overlap: int,
) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_doc_sentence_with_images(file_path: str, sentences_per_chunk: int) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_doc_page_aware_with_images(file_path: str, paragraphs_per_page: int) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_doc_structural_stream(file_path: str) -> DocStructuralIterator: ...
def chunk_doc_section_stream(file_path: str) -> DocSectionIterator: ...
def chunk_doc_semantic_stream(file_path: str) -> DocSemanticIterator: ...
def chunk_doc_sliding_window_stream(
    file_path: str, window_size: int, overlap: int,
) -> DocSlidingWindowIterator: ...
def chunk_doc_sentence_stream(
    file_path: str, sentences_per_chunk: int,
) -> DocSentenceIterator: ...
def chunk_doc_page_aware_stream(
    file_path: str, paragraphs_per_page: int,
) -> DocPageAwareIterator: ...
def doc_to_markdown(file_path: str) -> str: ...
def doc_to_markdown_with_images(file_path: str) -> tuple[str, list[tuple[str, bytes]]]: ...

# ── docx family ──────────────────────────────────────────────────────────────

def chunk_docx(file_path: str) -> dict[str, Any]: ...
def chunk_docx_section(file_path: str) -> dict[str, Any]: ...
def chunk_docx_semantic(file_path: str) -> dict[str, Any]: ...
def chunk_docx_sliding_window(file_path: str, window_size: int, overlap: int) -> dict[str, Any]: ...
def chunk_docx_sentence(file_path: str, sentences_per_chunk: int) -> dict[str, Any]: ...
def chunk_docx_page_aware(file_path: str, paragraphs_per_page: int) -> dict[str, Any]: ...
def chunk_docx_structural_with_images(file_path: str) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_docx_section_with_images(file_path: str) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_docx_semantic_with_images(file_path: str) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_docx_sliding_window_with_images(
    file_path: str, window_size: int, overlap: int,
) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_docx_sentence_with_images(file_path: str, sentences_per_chunk: int) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_docx_page_aware_with_images(file_path: str, paragraphs_per_page: int) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_docx_structural_stream(file_path: str) -> DocxStructuralIterator: ...
def chunk_docx_section_stream(file_path: str) -> DocxSectionIterator: ...
def chunk_docx_semantic_stream(file_path: str) -> DocxSemanticIterator: ...
def chunk_docx_sliding_window_stream(
    file_path: str, window_size: int, overlap: int,
) -> DocxSlidingWindowIterator: ...
def chunk_docx_sentence_stream(
    file_path: str, sentences_per_chunk: int,
) -> DocxSentenceIterator: ...
def chunk_docx_page_aware_stream(
    file_path: str, paragraphs_per_page: int,
) -> DocxPageAwareIterator: ...
def docx_to_markdown(file_path: str) -> str: ...
def docx_to_markdown_with_images(file_path: str) -> tuple[str, list[tuple[str, bytes]]]: ...

# ── eml / mbox ───────────────────────────────────────────────────────────────

def chunk_eml(file_path: str) -> dict[str, Any]: ...
def chunk_eml_section(file_path: str) -> dict[str, Any]: ...
def chunk_eml_semantic(file_path: str) -> dict[str, Any]: ...
def chunk_eml_sentence(file_path: str, sentences_per_chunk: int) -> dict[str, Any]: ...
def chunk_eml_page_aware(file_path: str, paragraphs_per_page: int) -> dict[str, Any]: ...
def chunk_eml_sliding_window(file_path: str, window_size: int, overlap: int) -> dict[str, Any]: ...
def chunk_eml_with_images(
    file_path: str, mode: str, rows_per_chunk: int, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int, max_chunk_chars: int,
) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def eml_to_markdown(file_path: str) -> str: ...
def eml_to_markdown_with_images(file_path: str) -> tuple[str, list[tuple[str, bytes]]]: ...
def stream_eml_chunks(
    file_path: str, mode: str, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int,
) -> _ChunkStreamIterator: ...

# ── epub ─────────────────────────────────────────────────────────────────────

def chunk_epub(file_path: str) -> dict[str, Any]: ...
def chunk_epub_section(file_path: str) -> dict[str, Any]: ...
def chunk_epub_semantic(file_path: str) -> dict[str, Any]: ...
def chunk_epub_sentence(file_path: str, sentences_per_chunk: int) -> dict[str, Any]: ...
def chunk_epub_page_aware(file_path: str, paragraphs_per_page: int) -> dict[str, Any]: ...
def chunk_epub_sliding_window(file_path: str, window_size: int, overlap: int) -> dict[str, Any]: ...
def chunk_epub_with_images(
    file_path: str, mode: str, rows_per_chunk: int, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int, max_chunk_chars: int,
) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def epub_to_markdown(file_path: str) -> str: ...
def epub_to_markdown_with_images(file_path: str) -> tuple[str, list[tuple[str, bytes]]]: ...
def stream_epub_chunks(
    file_path: str, mode: str, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int,
) -> _ChunkStreamIterator: ...

# ── html / htm ───────────────────────────────────────────────────────────────

def chunk_html(file_path: str) -> dict[str, Any]: ...
def chunk_html_structural(file_path: str) -> dict[str, Any]: ...
def chunk_html_section(file_path: str) -> dict[str, Any]: ...
def chunk_html_semantic(file_path: str) -> dict[str, Any]: ...
def chunk_html_sentence(file_path: str, sentences_per_chunk: int) -> dict[str, Any]: ...
def chunk_html_page_aware(file_path: str, paragraphs_per_page: int) -> dict[str, Any]: ...
def chunk_html_sliding_window(file_path: str, window_size: int, overlap: int) -> dict[str, Any]: ...
def chunk_html_with_images(
    file_path: str, mode: str, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int,
) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def html_to_markdown(file_path: str) -> str: ...
def html_to_markdown_with_images(file_path: str) -> tuple[str, list[tuple[str, bytes]]]: ...
def stream_html_chunks(
    file_path: str, mode: str, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int,
) -> _ChunkStreamIterator: ...

# ── ipynb ────────────────────────────────────────────────────────────────────

def chunk_ipynb(file_path: str) -> dict[str, Any]: ...
def chunk_ipynb_section(file_path: str) -> dict[str, Any]: ...
def chunk_ipynb_semantic(file_path: str) -> dict[str, Any]: ...
def chunk_ipynb_sentence(file_path: str, sentences_per_chunk: int) -> dict[str, Any]: ...
def chunk_ipynb_page_aware(file_path: str, paragraphs_per_page: int) -> dict[str, Any]: ...
def chunk_ipynb_sliding_window(file_path: str, window_size: int, overlap: int) -> dict[str, Any]: ...
def chunk_ipynb_with_images(
    file_path: str, mode: str, rows_per_chunk: int, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int, max_chunk_chars: int,
) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def ipynb_to_markdown(file_path: str) -> str: ...
def ipynb_to_markdown_with_images(file_path: str) -> tuple[str, list[tuple[str, bytes]]]: ...
def stream_ipynb_chunks(
    file_path: str, mode: str, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int,
) -> _ChunkStreamIterator: ...

# ── json / jsonl / ndjson ────────────────────────────────────────────────────

def chunk_json(file_path: str) -> dict[str, Any]: ...
def chunk_json_section(file_path: str) -> dict[str, Any]: ...
def chunk_json_semantic(file_path: str) -> dict[str, Any]: ...
def chunk_json_sentence(file_path: str, sentences_per_chunk: int) -> dict[str, Any]: ...
def chunk_json_page_aware(file_path: str, paragraphs_per_page: int) -> dict[str, Any]: ...
def chunk_json_sliding_window(file_path: str, window_size: int, overlap: int) -> dict[str, Any]: ...
def json_to_markdown(file_path: str) -> str: ...
def stream_json_chunks(
    file_path: str, mode: str, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int,
) -> _ChunkStreamIterator: ...

# ── md ───────────────────────────────────────────────────────────────────────

def chunk_md(file_path: str) -> dict[str, Any]: ...
def chunk_md_section(file_path: str) -> dict[str, Any]: ...
def chunk_md_semantic(file_path: str) -> dict[str, Any]: ...
def chunk_md_sentence(file_path: str, sentences_per_chunk: int) -> dict[str, Any]: ...
def chunk_md_page_aware(file_path: str, paragraphs_per_page: int) -> dict[str, Any]: ...
def chunk_md_sliding_window(file_path: str, window_size: int, overlap: int) -> dict[str, Any]: ...
def md_to_markdown(file_path: str) -> str: ...
def stream_md_chunks(
    file_path: str, mode: str, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int,
) -> _ChunkStreamIterator: ...

# ── msg (Outlook) ────────────────────────────────────────────────────────────

def chunk_msg(file_path: str) -> dict[str, Any]: ...
def chunk_msg_section(file_path: str) -> dict[str, Any]: ...
def chunk_msg_semantic(file_path: str) -> dict[str, Any]: ...
def chunk_msg_sentence(file_path: str, sentences_per_chunk: int) -> dict[str, Any]: ...
def chunk_msg_page_aware(file_path: str, paragraphs_per_page: int) -> dict[str, Any]: ...
def chunk_msg_sliding_window(file_path: str, window_size: int, overlap: int) -> dict[str, Any]: ...
def chunk_msg_with_images(
    file_path: str, mode: str, rows_per_chunk: int, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int, max_chunk_chars: int,
) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def msg_to_markdown(file_path: str) -> str: ...
def msg_to_markdown_with_images(file_path: str) -> tuple[str, list[tuple[str, bytes]]]: ...
def stream_msg_chunks(
    file_path: str, mode: str, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int,
) -> _ChunkStreamIterator: ...

# ── odf (odt / odp) ──────────────────────────────────────────────────────────

def chunk_odf(file_path: str) -> dict[str, Any]: ...
def chunk_odf_section(file_path: str) -> dict[str, Any]: ...
def chunk_odf_semantic(file_path: str) -> dict[str, Any]: ...
def chunk_odf_sentence(file_path: str, sentences_per_chunk: int) -> dict[str, Any]: ...
def chunk_odf_page_aware(file_path: str, paragraphs_per_page: int) -> dict[str, Any]: ...
def chunk_odf_sliding_window(file_path: str, window_size: int, overlap: int) -> dict[str, Any]: ...
def chunk_odf_with_images(
    file_path: str, mode: str, rows_per_chunk: int, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int, max_chunk_chars: int,
) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def odf_to_markdown(file_path: str) -> str: ...
def odf_to_markdown_with_images(file_path: str) -> tuple[str, list[tuple[str, bytes]]]: ...
def stream_odf_chunks(
    file_path: str, mode: str, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int,
) -> _ChunkStreamIterator: ...

# ── pdf ──────────────────────────────────────────────────────────────────────

def chunk_pdf(file_path: str) -> dict[str, Any]: ...
def chunk_pdf_fast(file_path: str) -> dict[str, Any]: ...
def chunk_pdf_structural(file_path: str) -> dict[str, Any]: ...
def chunk_pdf_section(file_path: str) -> dict[str, Any]: ...
def chunk_pdf_semantic(file_path: str) -> dict[str, Any]: ...
def chunk_pdf_sentence(file_path: str, sentences_per_chunk: int) -> dict[str, Any]: ...
def chunk_pdf_page_aware(file_path: str, paragraphs_per_page: int) -> dict[str, Any]: ...
def chunk_pdf_sliding_window(file_path: str, window_size: int, overlap: int) -> dict[str, Any]: ...
def chunk_pdf_with_images(
    file_path: str, mode: str, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int,
) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def pdf_to_markdown(file_path: str) -> str: ...
def pdf_to_markdown_with_images(file_path: str) -> tuple[str, list[tuple[str, bytes]]]: ...
def stream_pdf_chunks(
    file_path: str, mode: str, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int,
) -> _ChunkStreamIterator: ...

# ── ppt (PowerPoint 97-2003) ─────────────────────────────────────────────────

def chunk_ppt(file_path: str) -> dict[str, Any]: ...
def chunk_ppt_section(file_path: str) -> dict[str, Any]: ...
def chunk_ppt_semantic(file_path: str) -> dict[str, Any]: ...
def chunk_ppt_sliding_window(file_path: str, window_size: int, overlap: int) -> dict[str, Any]: ...
def chunk_ppt_sentence(file_path: str, sentences_per_chunk: int) -> dict[str, Any]: ...
def chunk_ppt_page_aware(file_path: str, paragraphs_per_page: int) -> dict[str, Any]: ...
def chunk_ppt_structural_with_images(file_path: str) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_ppt_section_with_images(file_path: str) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_ppt_semantic_with_images(file_path: str) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_ppt_sliding_window_with_images(
    file_path: str, window_size: int, overlap: int,
) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_ppt_sentence_with_images(file_path: str, sentences_per_chunk: int) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_ppt_page_aware_with_images(file_path: str, paragraphs_per_page: int) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_ppt_structural_stream(file_path: str) -> PptStructuralIterator: ...
def chunk_ppt_section_stream(file_path: str) -> PptSectionIterator: ...
def chunk_ppt_semantic_stream(file_path: str) -> PptSemanticIterator: ...
def chunk_ppt_sliding_window_stream(
    file_path: str, window_size: int, overlap: int,
) -> PptSlidingWindowIterator: ...
def chunk_ppt_sentence_stream(
    file_path: str, sentences_per_chunk: int,
) -> PptSentenceIterator: ...
def chunk_ppt_page_aware_stream(
    file_path: str, paragraphs_per_page: int,
) -> PptPageAwareIterator: ...
def ppt_to_markdown(file_path: str) -> str: ...
def ppt_to_markdown_with_images(file_path: str) -> tuple[str, list[tuple[str, bytes]]]: ...

# ── pptx family ──────────────────────────────────────────────────────────────

def chunk_pptx(file_path: str) -> dict[str, Any]: ...
def chunk_pptx_structural(file_path: str) -> dict[str, Any]: ...
def chunk_pptx_section(file_path: str) -> dict[str, Any]: ...
def chunk_pptx_semantic(file_path: str) -> dict[str, Any]: ...
def chunk_pptx_sliding_window(file_path: str, window_size: int, overlap: int) -> dict[str, Any]: ...
def chunk_pptx_sentence(file_path: str, sentences_per_chunk: int) -> dict[str, Any]: ...
def chunk_pptx_page_aware(file_path: str, paragraphs_per_page: int) -> dict[str, Any]: ...
def chunk_pptx_with_images(file_path: str) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_pptx_structural_with_images(file_path: str) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_pptx_section_with_images(file_path: str) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_pptx_semantic_with_images(file_path: str) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_pptx_sliding_window_with_images(
    file_path: str, window_size: int, overlap: int,
) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_pptx_sentence_with_images(file_path: str, sentences_per_chunk: int) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def chunk_pptx_page_aware_with_images(file_path: str, paragraphs_per_page: int) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def pptx_to_markdown(file_path: str) -> str: ...
def pptx_to_markdown_with_images(file_path: str) -> tuple[str, list[tuple[str, bytes]]]: ...
def stream_pptx_chunks(
    file_path: str, mode: str, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int,
) -> PptxStreamIterator: ...

# ── rtf ──────────────────────────────────────────────────────────────────────

def chunk_rtf(file_path: str) -> dict[str, Any]: ...
def chunk_rtf_section(file_path: str) -> dict[str, Any]: ...
def chunk_rtf_semantic(file_path: str) -> dict[str, Any]: ...
def chunk_rtf_sentence(file_path: str, sentences_per_chunk: int) -> dict[str, Any]: ...
def chunk_rtf_page_aware(file_path: str, paragraphs_per_page: int) -> dict[str, Any]: ...
def chunk_rtf_sliding_window(file_path: str, window_size: int, overlap: int) -> dict[str, Any]: ...
def rtf_to_markdown(file_path: str) -> str: ...
def stream_rtf_chunks(
    file_path: str, mode: str, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int,
) -> _ChunkStreamIterator: ...

# ── txt ──────────────────────────────────────────────────────────────────────

def chunk_txt(file_path: str) -> dict[str, Any]: ...
def chunk_txt_section(file_path: str) -> dict[str, Any]: ...
def chunk_txt_semantic(file_path: str) -> dict[str, Any]: ...
def chunk_txt_sentence(file_path: str, sentences_per_chunk: int) -> dict[str, Any]: ...
def chunk_txt_page_aware(file_path: str, paragraphs_per_page: int) -> dict[str, Any]: ...
def chunk_txt_sliding_window(file_path: str, window_size: int, overlap: int) -> dict[str, Any]: ...
def txt_to_markdown(file_path: str) -> str: ...
def stream_txt_chunks(
    file_path: str, mode: str, window_size: int, overlap: int,
    sentences_per_chunk: int, paragraphs_per_page: int,
) -> _ChunkStreamIterator: ...

# ── xlsx family ──────────────────────────────────────────────────────────────

def chunk_xlsx_row(
    file_path: str, rows_per_chunk: int, include_headers: bool,
    sheet_names: list[str], skip_empty_rows: bool,
) -> dict[str, Any]: ...
def chunk_xlsx_semantic(
    file_path: str, rows_per_chunk: int, include_headers: bool,
    sheet_names: list[str], skip_empty_rows: bool,
) -> dict[str, Any]: ...
def chunk_xlsx_table(
    file_path: str, include_headers: bool, sheet_names: list[str],
    skip_empty_rows: bool, max_chunk_chars: int,
) -> dict[str, Any]: ...
def chunk_xlsx_sheet(
    file_path: str, include_headers: bool, sheet_names: list[str],
    skip_empty_rows: bool, max_chunk_chars: int,
) -> dict[str, Any]: ...
def chunk_xlsx_page_aware(
    file_path: str, include_headers: bool, sheet_names: list[str],
    skip_empty_rows: bool, max_chunk_chars: int,
) -> dict[str, Any]: ...
def chunk_xlsx_sliding_window(
    file_path: str, window_size: int, overlap: int, include_headers: bool,
    sheet_names: list[str], skip_empty_rows: bool,
) -> dict[str, Any]: ...
def stream_xlsx_chunks(
    file_path: str, mode: str, rows_per_chunk: int, window_size: int, overlap: int,
    include_headers: bool, sheet_names: list[str], skip_empty_rows: bool,
    max_chunk_chars: int,
) -> XlsxStreamIterator: ...
def chunk_xlsx_with_images(
    file_path: str, mode: str, rows_per_chunk: int, window_size: int, overlap: int,
    include_headers: bool, sheet_names: list[str], skip_empty_rows: bool,
    max_chunk_chars: int,
) -> tuple[list[dict[str, Any]], list[tuple[str, bytes]]]: ...
def xlsx_to_markdown(file_path: str) -> str: ...
def xlsx_to_markdown_with_images(file_path: str) -> tuple[str, list[tuple[str, bytes]]]: ...
